#-------------------------------
# General Site Settings

title: Artists Theme
description: Thinker // Designer // YouTuber
email: artist@email

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}




#-------------------------------
# About Section


# NOTE: The avatar is defined in the all.sass document.


blurb: <p><strong>Travis specializes in making things</strong> for human people. Most of the things he makes are <a href="http://travisneilson.com">digital interfaces</a>, but he also puts effort into crafting <a href="http://soundcloud.com/travis-neilson">next-level beats</a> and <a href="http://youtube.com/user/devtipsfordesigners">YouTube videos</a> about making codes happen.</p>


skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}




#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1'}
- {name: City-IN website concept, folder: 'proj-2'}
- {name: Crispy Icons, folder: 'proj-3'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4'}
- {name: Fresh It Up, folder: 'proj-5'}
- {name: Timeline Page, folder: 'proj-6'}
- {name: Weather Dashboard, folder: 'proj-7'}
- {name: Stripes & Co, folder: 'proj-8'}




